### ISSUE TITLE
stew upgrade --all throwing errors

### ISSUE THREAD

**Issue by muralikodali** [marwanhawari/stew#10]
`stew upgrade --all` command throwing error, if there is no update found.
including this command in topgrade (r-darwish/topgrade) also throwing error status.
![screenshot_20220331214444](https://user-images.githubusercontent.com/11482766/161102151-a22522ec-8442-4a56-ab4f-a33f813774ea.png)

**Comment by edshamis** [comment]
Maybe better to print a warning? I've got a script to update everything and these error messages would just distract, giving no useful info

**Comment by edshamis** [comment]
Btw, the error message goes to stdout, not stderr

**Comment by marwanhawari** [comment]
These "errors" are harmless and more so just warnings.

> Btw, the error message goes to stdout, not stderr

Good call out! Started printing errors to stderr in #31
