### ISSUE TITLE
[Feature Request] Autoupdating Stewfile

### ISSUE THREAD

**Issue by kencx** [marwanhawari/stew#14]
Hi, thanks for stew, its been really useful.

I sync my Stewfile between workstations: when I install or update a binary on one PC, I manually regenerate a new Stewfile to propagate the changes to the other. 

Could we set a Stewfile to be updated automatically after every operation? Something like `stew file ~/dotfiles/Stewfile`. I could contribute a PR for this.

**Comment by marwanhawari** [comment]
If I understood you correctly, then the file you're looking for is `Stewfile.lock.json` which exists in the `stewPath`. The `Stewfile.lock.json` is pretty much a human-readable db for Stew. Every time you install/update/uninstall a binary, the `Stewfile.lock.json` gets updated.

The `Stewfile` was always meant to be easy to create, easy to destroy, and human-_writable_. If you only wanted to install a subset of your currently installed binaries, then you could manually write out a `Stewfile` or autogenerate one and remove the lines you didn't want.

Currently, you can't install from the `Stewfile.lock.json`, but I think that you should be able to.
Desired new behavior:
```
stew install /path/to/Stewfile.lock.json
```

I would be happy to review a PR that adds this feature.

**Comment by kencx** [comment]
this sounds good, I'll work on it over the weekend.
