### ISSUE TITLE
[Proposal] Extract binaries from archives

### ISSUE THREAD

**Issue by anuvyklack** [marwanhawari/stew#16]
It is common when, at release, a binary is packed with man file and some others into an archive. Like [zoxide](https://github.com/ajeetdsouza/zoxide), [btop](https://github.com/aristocratos/btop) and many others. It will be awesome if stew will be able to unpack such archives and allow choosing a binary to install.

**Comment by marwanhawari** [comment]
Stew is already able to do this! I can run `stew install ajeetdsouza/zoxide` and it will download the archive, extract the binary, and place it in the `stewBinPath`. If the binary isn't automatically detected, the user will be prompted to select it and potentially rename it.
