### ISSUE TITLE
renaming binaries

### ISSUE THREAD

**Issue by AFriemann** [marwanhawari/stew#3]
Hey again! opening another issue to keep things tidy.

A really nice addition would be the ability to store binaries under a different name, i.e. renaming a binary `foobar` to `kubectl-foobar`.

**Comment by FOSSforlife** [comment]
+1 to this, I was just going to post the same thing. It would also be great to have this feature added to the `Stewfile` so I can automate it.

**Comment by marwanhawari** [comment]
Yeah this is a good feature to have.

**Comment by marwanhawari** [comment]
I'm planning on automatically prompting the user to rename binaries in 2 scenarios:
1. The asset itself is the binary. Often these have names like `binary-v0.0.1-darwin-arm64`, which is not the name that people want to type into the command line.
2. If the binary is not automatically detected inside an archived asset (which can happen if 0 or >1 executable files are found in an archive). After selecting the binary, they will be prompted to rename it.

Other than that, I want a user to be able to rename a binary whenever they want by introducing a `rename` subcommand that will prompt the user for a new name
```
stew rename binary-v0.0.1-darwin-arm64
```

Is this what you all had in mind?
