### ISSUE TITLE
Support the XDG Base Directory Specification

### ISSUE THREAD

**Issue by marwanhawari** [marwanhawari/stew#4]
Currently `stew` stores all binaries and data in a `$HOME/.stew` directory but I would like to support the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) instead.

This would mean moving `~/.stew` to `$XDG_DATA_HOME/stew` (or `$HOME/.local/share/stew` if `$XDG_DATA_HOME` is not set).

**Comment by ComedyTomedy** [comment]
I'd love to have the option of putting binaries into `~/.local/bin/`; it would mean that (at least on systemd systems) there's no need to add anything to the `$PATH`.

(Aside - Just found you through Reddit, or rather, by googling for a github binary package manager, and this is exactly what I wanted, thank you ♥)

**Comment by marwanhawari** [comment]
Awesome, glad to hear it! My first priority is coming up with how I want to allow for user configuration, because right now custom configuration is not really possible. Once I settle on how `stew` will read and write user config, then I think I don't think it will be too difficult to allow users to change the location of the `stew` directory or change the binary install path.

**Comment by marwanhawari** [comment]
Resolved in https://github.com/marwanhawari/stew/pull/8
