### ISSUE TITLE
When searching for versions, try with and without a "v" prepended.

### ISSUE THREAD

**Issue by gdevenyi** [marwanhawari/stew#51]
Here I tried to install micro-editor:
```
$ stew install zyedidia/micro@2.0.14
zyedidia/micro
! Could not find a release with the tag 2.0.14 - please select a release:  [Use arrows to move, type to filter]
> nightly
  v2.0.14
  v2.0.14-rc1
  v2.0.13
  v2.0.12
  v2.0.11
  v2.0.10
```

Of course, 2.0.14 is right there, but they tagged it with a `v` and I didn't use that.

**Comment by marwanhawari** [comment]
I understand why you'd want this, but I'd rather keep the tag matching as is. It's more predictable and explicit the way it is now. Also, consider that sometimes tags aren't even versions, they're actual words.
